// <auto-generated />
namespace Juniors_Market.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IdnetityModelchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdnetityModelchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201902251914567_IdnetityModel changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
